/**
 * `ebb install` — write a launchd plist (macOS) or emit a systemd /
 * schtasks template (Linux / Windows).
 *
 * In --laptop mode we additionally drop a tiny helper script and
 * print the wake-event story; --server skips the wake step.
 */

import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { homedir } from "node:os";
import {
  currentPlatform,
  type PlatformName,
} from "../platform/index.js";
import { launchdPlist } from "../platform/macos.js";
import { systemdServiceTemplate } from "../platform/linux.js";
import { schtasksTemplate } from "../platform/windows.js";
import { defaultDbPath } from "./tick.js";

export type InstallMode = "laptop" | "server";

export interface InstallOptions {
  mode: InstallMode;
  /** Override platform detection (tests). */
  platform?: PlatformName;
  /** Override the `ebb` binary path (tests). */
  ebbBinaryPath?: string;
  /** Override the SQLite path (tests). */
  dbPath?: string;
  /** Override the tick interval. Defaults to 300s. */
  tickIntervalSec?: number;
  /** If true, do not write any files; only return the rendered strings. */
  dryRun?: boolean;
}

export interface InstallArtifacts {
  platform: PlatformName;
  /** Path that would be written, or "" for non-macOS. */
  plistPath: string;
  /** The rendered plist XML, or "" for non-macOS. */
  plistContent: string;
  /** Path for the laptop-wake helper script, or "" if --server or non-macOS. */
  helperPath: string;
  /** Rendered helper script content, or "" if --server or non-macOS. */
  helperContent: string;
  /** Human-facing next-steps message. */
  nextSteps: string;
}

function ebbBinaryPath(override?: string): string {
  if (override) return override;
  // Resolve relative to the running CLI when possible. Otherwise default
  // to the workspace `dist` path so a fresh checkout works.
  const env = process.env.EBB_BINARY;
  if (env) return env;
  return "/usr/local/bin/ebb";
}

function helperScript(opts: { ebbBinaryPath: string; dbPath: string }): string {
  return `#!/usr/bin/env bash
# laptop-wake.sh — register pmset wake events for newly-scheduled ebb tasks.
# Generated by \`ebb install --laptop\`. Re-run any time.

set -euo pipefail

DB="${opts.dbPath}"
EBB="${opts.ebbBinaryPath}"

# List currently-scheduled tasks (status=scheduled). For each, pre-register
# a wake event 30s before the chosen window. Requires sudoers entry for
# pmset; \`ebb register-wake\` prints the exact command if not.
"$EBB" queue list --status scheduled | tail -n +2 | awk '{print $1}' | while read -r TASK_ID; do
  "$EBB" register-wake "$TASK_ID" || true
done
`;
}

export async function runInstall(opts: InstallOptions): Promise<InstallArtifacts> {
  const platform = opts.platform ?? currentPlatform();
  const binary = ebbBinaryPath(opts.ebbBinaryPath);
  const dbPath = opts.dbPath ?? defaultDbPath();
  const tickInterval = opts.tickIntervalSec ?? 300;

  if (platform === "macos") {
    const plistContent = launchdPlist({
      tickIntervalSec: tickInterval,
      ebbBinaryPath: binary,
      dbPath,
    });
    const plistPath = join(
      homedir(),
      "Library",
      "LaunchAgents",
      "com.ebb-ai.tick.plist",
    );
    const helperContent =
      opts.mode === "laptop" ? helperScript({ ebbBinaryPath: binary, dbPath }) : "";
    const helperPath =
      opts.mode === "laptop"
        ? join(homedir(), ".ebb", "laptop-wake.sh")
        : "";

    if (!opts.dryRun) {
      mkdirSync(dirname(plistPath), { recursive: true });
      writeFileSync(plistPath, plistContent, "utf8");
      mkdirSync(dirname(dbPath), { recursive: true });
      if (helperPath) {
        mkdirSync(dirname(helperPath), { recursive: true });
        writeFileSync(helperPath, helperContent, { encoding: "utf8", mode: 0o755 });
      }
    }

    const wakeNote =
      opts.mode === "laptop"
        ? `\n3. Pre-register wake events as tasks are scheduled:\n` +
          `     ${helperPath}\n` +
          `   (Requires a sudoers entry for \`pmset schedule wake\`.)`
        : "";
    const nextSteps =
      `Wrote ${plistPath}.\n\n` +
      `Next steps:\n` +
      `1. Reload launchd:\n` +
      `     launchctl load ${plistPath}\n` +
      `2. (optional) Tail the log:\n` +
      `     tail -f ~/.ebb/tick.log${wakeNote}\n`;

    return {
      platform,
      plistPath,
      plistContent,
      helperPath,
      helperContent,
      nextSteps,
    };
  }

  if (platform === "linux") {
    const template = systemdServiceTemplate({
      ebbBinaryPath: binary,
      dbPath,
      tickIntervalSec: tickInterval,
    });
    return {
      platform,
      plistPath: "",
      plistContent: "",
      helperPath: "",
      helperContent: "",
      nextSteps: template,
    };
  }

  // windows
  const template = schtasksTemplate({
    ebbBinaryPath: binary,
    dbPath,
    tickIntervalSec: tickInterval,
  });
  return {
    platform,
    plistPath: "",
    plistContent: "",
    helperPath: "",
    helperContent: "",
    nextSteps: template,
  };
}
